services :

  jenkins :
    image : jenkins/jenkins:lts
    privileged : true
    user : root
    ports :
      - "8080:8080"
      - "50000:50000"
    volumes :
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  prometheus :
    image : prom/prometheus
    ports :
      - "9090:9090"
    volumes :
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana :
    image : grafana/grafana
    ports :
      - "3000:3000"
    depends_on:
      - prometheus
    
volumes :
  jenkins_data :
      